/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class shaded_org_evosuite_ga_metaheuristics_NCDShocZlib */

#ifndef _Included_shaded_org_evosuite_ga_metaheuristics_NCDShocZlib
#define _Included_shaded_org_evosuite_ga_metaheuristics_NCDShocZlib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     shaded_org_evosuite_ga_metaheuristics_NCDShocZlib
 * Method:    ncd
 * Signature: (Ljava/lang/String;JLjava/lang/String;JLjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_shaded_org_evosuite_ga_metaheuristics_NCDShocZlib_ncd
  (JNIEnv *, jobject, jstring, jlong, jstring, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
